# backend/Dockerfile.dev
FROM node:20

# Crée un dossier de travail
WORKDIR /app

# Copie package.json et package-lock.json
COPY package*.json ./

# Installe TOUTES les dépendances (y compris devDependencies comme nodemon)
RUN npm install

# Copie le reste du code
COPY . .

# Expose le port de l’API
EXPOSE 5000

# Commande par défaut → sera remplacée par docker-compose.override.yml (npm run dev)
CMD ["npm", "run", "dev"]
